window.JACKIE_EDITABLE_CONFIG = {
  meta: {
    title: "Oren",
    description: "Welcome to My World.",
  },

  text: {
    "tirelessly pursue clarity.": "Aesthetic judgment matters",
    "Software should empower.": "Content drives growth",
    "Design for moments": "Turn AI into tools",
  },

  links: {
    // Example:
    // "./work": "#work",
    // "mailto:hello@example.com": "mailto:you@example.com",
  },

  images: {
    // Use part of the original image URL as the key, and your local/remote image path as the value.
    // Example:
    // "0Kj6KlVZPILk9uoSPK7tmq8hGJU.png": "./assets/your-project-image.png",
    "JnX4DQ93dVEHzTFGkUsZLNV4.png": "./assets/oren-side-icon-stamp-v1.png",
    "RYvnMMGEz4Ds3BGL5W1lRp9GOCU.png": "./assets/oren-side-icon-bowl-v1.png",
    "zs8DG1Zf6J6s1d5yc00xHp98b60.png": "./assets/oren-side-icon-digital-v1.png",
    "X8TlTAmfaqh8FaOYxjSjYMniaE.png": "./assets/oren-side-icon-sprig-v1.png",
    "2LGPmWLUdShRmg0q79YvdcxivM.png": "./assets/oren-side-icon-sprig-v1.png",
    "jvHISkS7qP9hkgBbgfRCAiPpjjI.png": "./assets/oren-side-icon-sprig-v1.png",
    "J4bjhr8zDlxffN0kZnWBShva0GY.png": "./assets/oren-side-icon-night-v1.png",
    "z0ha6Cap1xjkHBWyu1iV9tnWBNQ.png": "./assets/oren-side-icon-bowl-v1.png",
    "uNzaxXZLk1aHsF3AXi7f4aGR0g.png": "./assets/oren-side-doodle-juicebox-v1.png",
    "qe4YBLLmBViMAbL2fiphUNfdxA.png": "./assets/oren-side-doodle-orbit-bowl-v1.png",
    "DUDVhZzaglA4vXZTKvTA6gePrU.png": "./assets/oren-side-doodle-househead-v1.png",
    "afys4KtZC007XBhmTWURY9KL4.png": "./assets/ai-color-match-visual-control-v1.png?v=20260531-v2",
    "UeG3qBVgjLwvwcGSGQLZM9AI.png": "./assets/ai-scene-portfolio-square-v1.png?v=20260531-v1",
    "x3y7QRdmiIS5JFAwhWC4IHHHJsE.png": "./assets/ai-lab-relight-slow-shutter-poster-v1.png?v=20260531-v1",
    "Wiw196PFt5v5LcQxgcrCUB3F0.png": "./assets/liangjian-proposal-cover-v8.png?v=20260529-v1",
    "JCVH1U71jmRJSgalqgIDAfuO8.png": "./assets/kuaishou-proposal-cover-v7.png?v=20260529-v1",
    "qPdyyjiGVcYhSJZ659iudjEFmbw.png": "./assets/assassin-proposal-cover-v1.png?v=20260529-v1",
    "JiCsfFAbrVrZSX3x7Y9dkgzckI.png": "./assets/postal-proposal-cover-v1.png?v=20260529-v2",
  },

  galleries: {
    "Wiw196PFt5v5LcQxgcrCUB3F0.png": {
      title: "亮简行动",
      previewTitle: "亮简行动（利郎男装）",
      subtitle: "利郎男装广告策划案",
      award: "学院奖-广告策划类-国家级二等奖",
      images: [
        "./assets/liangjian-proposal-pages/page-01.png",
        "./assets/liangjian-proposal-pages/page-02.png",
        "./assets/liangjian-proposal-pages/page-03.png",
        "./assets/liangjian-proposal-pages/page-04.png",
        "./assets/liangjian-proposal-pages/page-05.png",
        "./assets/liangjian-proposal-pages/page-06.png",
        "./assets/liangjian-proposal-pages/page-07.png",
        "./assets/liangjian-proposal-pages/page-08.png",
        "./assets/liangjian-proposal-pages/page-09.png",
        "./assets/liangjian-proposal-pages/page-10.png",
        "./assets/liangjian-proposal-pages/page-11.png",
        "./assets/liangjian-proposal-pages/page-12.png",
        "./assets/liangjian-proposal-pages/page-13.png",
        "./assets/liangjian-proposal-pages/page-14.png",
        "./assets/liangjian-proposal-pages/page-15.png",
        "./assets/liangjian-proposal-pages/page-16.png",
        "./assets/liangjian-proposal-pages/page-17.png",
        "./assets/liangjian-proposal-pages/page-18.png",
        "./assets/liangjian-proposal-pages/page-19.png",
        "./assets/liangjian-proposal-pages/page-20.png",
        "./assets/liangjian-proposal-pages/page-21.png",
        "./assets/liangjian-proposal-pages/page-22.png",
        "./assets/liangjian-proposal-pages/page-23.png",
        "./assets/liangjian-proposal-pages/page-24.png",
        "./assets/liangjian-proposal-pages/page-25.png",
        "./assets/liangjian-proposal-pages/page-26.png",
        "./assets/liangjian-proposal-pages/page-27.png",
        "./assets/liangjian-proposal-pages/page-28.png",
        "./assets/liangjian-proposal-pages/page-29.png",
        "./assets/liangjian-proposal-pages/page-30.png",
      ],
    },
    "JCVH1U71jmRJSgalqgIDAfuO8.png": {
      title: "生活交“享”乐",
      previewTitle: "生活交“享”乐（快手）",
      subtitle: "快手广告营销向策划案",
      award: "大广赛-广告策划类-国家级和山东省优秀奖",
      images: [
        "./assets/kuaishou-proposal-pages-v2/page-01.png",
        "./assets/kuaishou-proposal-pages-v2/page-02.png",
        "./assets/kuaishou-proposal-pages-v2/page-03.png",
        "./assets/kuaishou-proposal-pages-v2/page-04.png",
        "./assets/kuaishou-proposal-pages-v2/page-05.png",
        "./assets/kuaishou-proposal-pages-v2/page-06.png",
        "./assets/kuaishou-proposal-pages-v2/page-07.png",
        "./assets/kuaishou-proposal-pages-v2/page-08.png",
        "./assets/kuaishou-proposal-pages-v2/page-09.png",
        "./assets/kuaishou-proposal-pages-v2/page-10.png",
        "./assets/kuaishou-proposal-pages-v2/page-11.png",
        "./assets/kuaishou-proposal-pages-v2/page-12.png",
        "./assets/kuaishou-proposal-pages-v2/page-13.png",
        "./assets/kuaishou-proposal-pages-v2/page-14.png",
        "./assets/kuaishou-proposal-pages-v2/page-15.png",
        "./assets/kuaishou-proposal-pages-v2/page-16.png",
        "./assets/kuaishou-proposal-pages-v2/page-17.png",
        "./assets/kuaishou-proposal-pages-v2/page-18.png",
        "./assets/kuaishou-proposal-pages-v2/page-19.png",
        "./assets/kuaishou-proposal-pages-v2/page-20.png",
        "./assets/kuaishou-proposal-pages-v2/page-21.png",
        "./assets/kuaishou-proposal-pages-v2/page-22.png",
        "./assets/kuaishou-proposal-pages-v2/page-23.png",
        "./assets/kuaishou-proposal-pages-v2/page-24.png",
        "./assets/kuaishou-proposal-pages-v2/page-25.png",
        "./assets/kuaishou-proposal-pages-v2/page-26.png",
        "./assets/kuaishou-proposal-pages-v2/page-27.png",
        "./assets/kuaishou-proposal-pages-v2/page-28.png",
        "./assets/kuaishou-proposal-pages-v2/page-29.png",
      ],
    },
    "qPdyyjiGVcYhSJZ659iudjEFmbw.png": {
      title: "我不是刺客",
      previewTitle: "我不是刺客（泡泡玛特）",
      subtitle: "泡泡玛特营销策划案",
      award: "大广赛-广告策划类-山东省二等奖",
      spreadSize: 1,
      images: [
        "./assets/assassin-proposal-pages/page-01.png",
        "./assets/assassin-proposal-pages/page-02.png",
        "./assets/assassin-proposal-pages/page-03.png",
        "./assets/assassin-proposal-pages/page-04.png",
        "./assets/assassin-proposal-pages/page-05.png",
        "./assets/assassin-proposal-pages/page-06.png",
        "./assets/assassin-proposal-pages/page-07.png",
        "./assets/assassin-proposal-pages/page-08.png",
        "./assets/assassin-proposal-pages/page-09.png",
        "./assets/assassin-proposal-pages/page-10.png",
        "./assets/assassin-proposal-pages/page-11.png",
        "./assets/assassin-proposal-pages/page-12.png",
        "./assets/assassin-proposal-pages/page-13.png",
        "./assets/assassin-proposal-pages/page-14.png",
        "./assets/assassin-proposal-pages/page-15.png",
        "./assets/assassin-proposal-pages/page-16.png",
        "./assets/assassin-proposal-pages/page-17.png",
        "./assets/assassin-proposal-pages/page-18.png",
        "./assets/assassin-proposal-pages/page-19.png",
        "./assets/assassin-proposal-pages/page-20.png",
        "./assets/assassin-proposal-pages/page-21.png",
        "./assets/assassin-proposal-pages/page-22.png",
        "./assets/assassin-proposal-pages/page-23.png",
        "./assets/assassin-proposal-pages/page-24.png",
        "./assets/assassin-proposal-pages/page-25.png",
        "./assets/assassin-proposal-pages/page-26.png",
        "./assets/assassin-proposal-pages/page-27.png",
        "./assets/assassin-proposal-pages/page-28.png",
        "./assets/assassin-proposal-pages/page-29.png",
        "./assets/assassin-proposal-pages/page-30.png",
        "./assets/assassin-proposal-pages/page-31.png",
        "./assets/assassin-proposal-pages/page-32.png",
      ],
    },
    "JiCsfFAbrVrZSX3x7Y9dkgzckI.png": {
      title: "邮你在，币不同",
      previewTitle: "邮你在，币不同（邮储银行）",
      subtitle: "邮储银行广告策划案",
      award: "大广节-广告策划类-入围奖",
      spreadSize: 1,
      images: [
        "./assets/postal-proposal-pages/page-01.png",
        "./assets/postal-proposal-pages/page-02.png",
        "./assets/postal-proposal-pages/page-03.png",
        "./assets/postal-proposal-pages/page-04.png",
        "./assets/postal-proposal-pages/page-05.png",
        "./assets/postal-proposal-pages/page-06.png",
        "./assets/postal-proposal-pages/page-07.png",
        "./assets/postal-proposal-pages/page-08.png",
        "./assets/postal-proposal-pages/page-09.png",
        "./assets/postal-proposal-pages/page-10.png",
        "./assets/postal-proposal-pages/page-11.png",
        "./assets/postal-proposal-pages/page-12.png",
        "./assets/postal-proposal-pages/page-13.png",
        "./assets/postal-proposal-pages/page-14.png",
        "./assets/postal-proposal-pages/page-15.png",
        "./assets/postal-proposal-pages/page-16.png",
        "./assets/postal-proposal-pages/page-17.png",
        "./assets/postal-proposal-pages/page-18.png",
        "./assets/postal-proposal-pages/page-19.png",
        "./assets/postal-proposal-pages/page-20.png",
        "./assets/postal-proposal-pages/page-21.png",
        "./assets/postal-proposal-pages/page-22.png",
        "./assets/postal-proposal-pages/page-23.png",
        "./assets/postal-proposal-pages/page-24.png",
        "./assets/postal-proposal-pages/page-25.png",
        "./assets/postal-proposal-pages/page-26.png",
      ],
    },
  },

  behavior: {
    keepOriginalMotion: true,
    desktopFirst: true,
  },
};
