window.JACKIE_EDITABLE_CONFIG = {
  meta: {
    title: "Oren",
    description: "Welcome to My World.",
  },

  text: {
    "tirelessly pursue clarity.": "Aesthetic judgment matters",
    "Software should empower.": "Content drives growth",
    "Design for moments": "Turn AI into tools",
  },

  links: {
    // Example:
    // "./work": "#work",
    // "./contact": "mailto:xuhaocheng.xmu@vip.163.com",
  },

  images: {
    // Use part of the original image URL as the key, and your local/remote image path as the value.
    // Example:
    // "0Kj6KlVZPILk9uoSPK7tmq8hGJU.png": "./assets/your-project-image.png",
    "JnX4DQ93dVEHzTFGkUsZLNV4.png": "./assets-optimized/oren-side-icon-stamp-v1.webp",
    "RYvnMMGEz4Ds3BGL5W1lRp9GOCU.png": "./assets-optimized/oren-side-icon-bowl-v1.webp",
    "zs8DG1Zf6J6s1d5yc00xHp98b60.png": "./assets-optimized/oren-side-icon-digital-v1.webp",
    "X8TlTAmfaqh8FaOYxjSjYMniaE.png": "./assets-optimized/oren-side-icon-sprig-v1.webp",
    "2LGPmWLUdShRmg0q79YvdcxivM.png": "./assets-optimized/oren-side-icon-sprig-v1.webp",
    "jvHISkS7qP9hkgBbgfRCAiPpjjI.png": "./assets-optimized/oren-side-icon-sprig-v1.webp",
    "J4bjhr8zDlxffN0kZnWBShva0GY.png": "./assets-optimized/oren-side-icon-night-v1.webp",
    "z0ha6Cap1xjkHBWyu1iV9tnWBNQ.png": "./assets-optimized/oren-side-icon-bowl-v1.webp",
    "uNzaxXZLk1aHsF3AXi7f4aGR0g.png": "./assets-optimized/oren-side-doodle-juicebox-v1.webp",
    "qe4YBLLmBViMAbL2fiphUNfdxA.png": "./assets-optimized/oren-side-doodle-orbit-bowl-v1.webp",
    "DUDVhZzaglA4vXZTKvTA6gePrU.png": "./assets-optimized/oren-side-doodle-househead-v1.webp",
    "afys4KtZC007XBhmTWURY9KL4.png": "./assets-optimized/ai-color-match-visual-control-v1.jpg?v=20260531-v2",
    "UeG3qBVgjLwvwcGSGQLZM9AI.png": "./assets-optimized/ai-scene-portfolio-square-v1.jpg?v=20260531-v1",
    "x3y7QRdmiIS5JFAwhWC4IHHHJsE.png": "./assets-optimized/ai-lab-relight-slow-shutter-poster-v1.jpg?v=20260531-v1",
    "Wiw196PFt5v5LcQxgcrCUB3F0.png": "./assets-optimized/liangjian-proposal-cover-v8.jpg?v=20260529-v1",
    "JCVH1U71jmRJSgalqgIDAfuO8.png": "./assets-optimized/kuaishou-proposal-cover-v7.jpg?v=20260529-v1",
    "qPdyyjiGVcYhSJZ659iudjEFmbw.png": "./assets-optimized/assassin-proposal-cover-v1.jpg?v=20260529-v1",
    "JiCsfFAbrVrZSX3x7Y9dkgzckI.png": "./assets-optimized/postal-proposal-cover-v1.jpg?v=20260529-v2",
  },

  galleries: {
    "Wiw196PFt5v5LcQxgcrCUB3F0.png": {
      title: "亮简行动",
      previewTitle: "亮简行动（利郎男装）",
      subtitle: "利郎男装广告策划案",
      award: "学院奖-广告策划类-国家级二等奖",
      images: [
        "./assets-optimized/liangjian-proposal-pages/page-01.jpg",
        "./assets-optimized/liangjian-proposal-pages/page-02.jpg",
        "./assets-optimized/liangjian-proposal-pages/page-03.jpg",
        "./assets-optimized/liangjian-proposal-pages/page-04.jpg",
        "./assets-optimized/liangjian-proposal-pages/page-05.jpg",
        "./assets-optimized/liangjian-proposal-pages/page-06.jpg",
        "./assets-optimized/liangjian-proposal-pages/page-07.jpg",
        "./assets-optimized/liangjian-proposal-pages/page-08.jpg",
        "./assets-optimized/liangjian-proposal-pages/page-09.jpg",
        "./assets-optimized/liangjian-proposal-pages/page-10.jpg",
        "./assets-optimized/liangjian-proposal-pages/page-11.jpg",
        "./assets-optimized/liangjian-proposal-pages/page-12.jpg",
        "./assets-optimized/liangjian-proposal-pages/page-13.jpg",
        "./assets-optimized/liangjian-proposal-pages/page-14.jpg",
        "./assets-optimized/liangjian-proposal-pages/page-15.jpg",
        "./assets-optimized/liangjian-proposal-pages/page-16.jpg",
        "./assets-optimized/liangjian-proposal-pages/page-17.jpg",
        "./assets-optimized/liangjian-proposal-pages/page-18.jpg",
        "./assets-optimized/liangjian-proposal-pages/page-19.jpg",
        "./assets-optimized/liangjian-proposal-pages/page-20.jpg",
        "./assets-optimized/liangjian-proposal-pages/page-21.jpg",
        "./assets-optimized/liangjian-proposal-pages/page-22.jpg",
        "./assets-optimized/liangjian-proposal-pages/page-23.jpg",
        "./assets-optimized/liangjian-proposal-pages/page-24.jpg",
        "./assets-optimized/liangjian-proposal-pages/page-25.jpg",
        "./assets-optimized/liangjian-proposal-pages/page-26.jpg",
        "./assets-optimized/liangjian-proposal-pages/page-27.jpg",
        "./assets-optimized/liangjian-proposal-pages/page-28.jpg",
        "./assets-optimized/liangjian-proposal-pages/page-29.jpg",
        "./assets-optimized/liangjian-proposal-pages/page-30.jpg",
      ],
    },
    "JCVH1U71jmRJSgalqgIDAfuO8.png": {
      title: "生活交“享”乐",
      previewTitle: "生活交“享”乐（快手）",
      subtitle: "快手广告营销向策划案",
      award: "大广赛-广告策划类-国家级和山东省优秀奖",
      images: [
        "./assets-optimized/kuaishou-proposal-pages-v2/page-01.jpg",
        "./assets-optimized/kuaishou-proposal-pages-v2/page-02.jpg",
        "./assets-optimized/kuaishou-proposal-pages-v2/page-03.jpg",
        "./assets-optimized/kuaishou-proposal-pages-v2/page-04.jpg",
        "./assets-optimized/kuaishou-proposal-pages-v2/page-05.jpg",
        "./assets-optimized/kuaishou-proposal-pages-v2/page-06.jpg",
        "./assets-optimized/kuaishou-proposal-pages-v2/page-07.jpg",
        "./assets-optimized/kuaishou-proposal-pages-v2/page-08.jpg",
        "./assets-optimized/kuaishou-proposal-pages-v2/page-09.jpg",
        "./assets-optimized/kuaishou-proposal-pages-v2/page-10.jpg",
        "./assets-optimized/kuaishou-proposal-pages-v2/page-11.jpg",
        "./assets-optimized/kuaishou-proposal-pages-v2/page-12.jpg",
        "./assets-optimized/kuaishou-proposal-pages-v2/page-13.jpg",
        "./assets-optimized/kuaishou-proposal-pages-v2/page-14.jpg",
        "./assets-optimized/kuaishou-proposal-pages-v2/page-15.jpg",
        "./assets-optimized/kuaishou-proposal-pages-v2/page-16.jpg",
        "./assets-optimized/kuaishou-proposal-pages-v2/page-17.jpg",
        "./assets-optimized/kuaishou-proposal-pages-v2/page-18.jpg",
        "./assets-optimized/kuaishou-proposal-pages-v2/page-19.jpg",
        "./assets-optimized/kuaishou-proposal-pages-v2/page-20.jpg",
        "./assets-optimized/kuaishou-proposal-pages-v2/page-21.jpg",
        "./assets-optimized/kuaishou-proposal-pages-v2/page-22.jpg",
        "./assets-optimized/kuaishou-proposal-pages-v2/page-23.jpg",
        "./assets-optimized/kuaishou-proposal-pages-v2/page-24.jpg",
        "./assets-optimized/kuaishou-proposal-pages-v2/page-25.jpg",
        "./assets-optimized/kuaishou-proposal-pages-v2/page-26.jpg",
        "./assets-optimized/kuaishou-proposal-pages-v2/page-27.jpg",
        "./assets-optimized/kuaishou-proposal-pages-v2/page-28.jpg",
        "./assets-optimized/kuaishou-proposal-pages-v2/page-29.jpg",
      ],
    },
    "qPdyyjiGVcYhSJZ659iudjEFmbw.png": {
      title: "我不是刺客",
      previewTitle: "我不是刺客（泡泡玛特）",
      subtitle: "泡泡玛特营销策划案",
      award: "大广赛-广告策划类-山东省二等奖",
      spreadSize: 1,
      images: [
        "./assets-optimized/assassin-proposal-pages/page-01.jpg",
        "./assets-optimized/assassin-proposal-pages/page-02.jpg",
        "./assets-optimized/assassin-proposal-pages/page-03.jpg",
        "./assets-optimized/assassin-proposal-pages/page-04.jpg",
        "./assets-optimized/assassin-proposal-pages/page-05.jpg",
        "./assets-optimized/assassin-proposal-pages/page-06.jpg",
        "./assets-optimized/assassin-proposal-pages/page-07.jpg",
        "./assets-optimized/assassin-proposal-pages/page-08.jpg",
        "./assets-optimized/assassin-proposal-pages/page-09.jpg",
        "./assets-optimized/assassin-proposal-pages/page-10.jpg",
        "./assets-optimized/assassin-proposal-pages/page-11.jpg",
        "./assets-optimized/assassin-proposal-pages/page-12.jpg",
        "./assets-optimized/assassin-proposal-pages/page-13.jpg",
        "./assets-optimized/assassin-proposal-pages/page-14.jpg",
        "./assets-optimized/assassin-proposal-pages/page-15.jpg",
        "./assets-optimized/assassin-proposal-pages/page-16.jpg",
        "./assets-optimized/assassin-proposal-pages/page-17.jpg",
        "./assets-optimized/assassin-proposal-pages/page-18.jpg",
        "./assets-optimized/assassin-proposal-pages/page-19.jpg",
        "./assets-optimized/assassin-proposal-pages/page-20.jpg",
        "./assets-optimized/assassin-proposal-pages/page-21.jpg",
        "./assets-optimized/assassin-proposal-pages/page-22.jpg",
        "./assets-optimized/assassin-proposal-pages/page-23.jpg",
        "./assets-optimized/assassin-proposal-pages/page-24.jpg",
        "./assets-optimized/assassin-proposal-pages/page-25.jpg",
        "./assets-optimized/assassin-proposal-pages/page-26.jpg",
        "./assets-optimized/assassin-proposal-pages/page-27.jpg",
        "./assets-optimized/assassin-proposal-pages/page-28.jpg",
        "./assets-optimized/assassin-proposal-pages/page-29.jpg",
        "./assets-optimized/assassin-proposal-pages/page-30.jpg",
        "./assets-optimized/assassin-proposal-pages/page-31.jpg",
        "./assets-optimized/assassin-proposal-pages/page-32.jpg",
      ],
    },
    "JiCsfFAbrVrZSX3x7Y9dkgzckI.png": {
      title: "邮你在，币不同",
      previewTitle: "邮你在，币不同（邮储银行）",
      subtitle: "邮储银行广告策划案",
      award: "大广节-广告策划类-入围奖",
      spreadSize: 1,
      images: [
        "./assets-optimized/postal-proposal-pages/page-01.jpg",
        "./assets-optimized/postal-proposal-pages/page-02.jpg",
        "./assets-optimized/postal-proposal-pages/page-03.jpg",
        "./assets-optimized/postal-proposal-pages/page-04.jpg",
        "./assets-optimized/postal-proposal-pages/page-05.jpg",
        "./assets-optimized/postal-proposal-pages/page-06.jpg",
        "./assets-optimized/postal-proposal-pages/page-07.jpg",
        "./assets-optimized/postal-proposal-pages/page-08.jpg",
        "./assets-optimized/postal-proposal-pages/page-09.jpg",
        "./assets-optimized/postal-proposal-pages/page-10.jpg",
        "./assets-optimized/postal-proposal-pages/page-11.jpg",
        "./assets-optimized/postal-proposal-pages/page-12.jpg",
        "./assets-optimized/postal-proposal-pages/page-13.jpg",
        "./assets-optimized/postal-proposal-pages/page-14.jpg",
        "./assets-optimized/postal-proposal-pages/page-15.jpg",
        "./assets-optimized/postal-proposal-pages/page-16.jpg",
        "./assets-optimized/postal-proposal-pages/page-17.jpg",
        "./assets-optimized/postal-proposal-pages/page-18.jpg",
        "./assets-optimized/postal-proposal-pages/page-19.jpg",
        "./assets-optimized/postal-proposal-pages/page-20.jpg",
        "./assets-optimized/postal-proposal-pages/page-21.jpg",
        "./assets-optimized/postal-proposal-pages/page-22.jpg",
        "./assets-optimized/postal-proposal-pages/page-23.jpg",
        "./assets-optimized/postal-proposal-pages/page-24.jpg",
        "./assets-optimized/postal-proposal-pages/page-25.jpg",
        "./assets-optimized/postal-proposal-pages/page-26.jpg",
      ],
    },
  },

  behavior: {
    keepOriginalMotion: true,
    desktopFirst: true,
  },
};
